# ============================
# DIY-Ruleset 配置示例 
# ============================
global:
  enable_gh_proxy: true                # 是否在 README 报表中为下载链接添加 GitHub 加速链接
  gh_proxy: "https://v6.gh-proxy.org/" # GitHub 加速前缀
  split_cnip: true                     # 是否生成 CNIPv4/CNIPv6 文件
  # 全局默认的输出开关与特性。所有 Category 都会默认继承这里的设置。
  singbox:
    enable: true             # 是否生成 Sing-box 文件，总开关
    json: true               # 是否生成 JSON 格式文件
    srs: true                # 是否生成 SRS  格式文件
    single_file: false       # true将域名和IP合并为一个文件; false拆分为 主文件名.srs 和 主文件名ip.srs
  mihomo:
    enable: true             # 是否生成 Mihomo (Clash Meta) 文件，总开关
    list: true               # 是否生成 Classical List 格式文件
    yaml: false              # 是否生成 YAML 格式文件
    mrs: true                # 是否生成 MRS  格式文件
    single_file: false       # true合并域名和IP; false拆分为 主文件名.mrs 和 主文件名ip.mrs，注：mrs 文件不支持合并，开启也会拆分！
  v2ray:        {enable: true, single_file: false}
  surge:        {enable: true, single_file: true}
  loon:         {enable: true, single_file: true}
  stash:        {enable: true, single_file: true}
  egern:        {enable: true, single_file: true}
  shadowrocket: {enable: true, single_file: true}
  quantumultx:  {enable: true, single_file: true}

# ============================
# 规则集配置 (Categories)
# ============================
categories:
  # 示例 1：常规规则集 (继承全局，无特殊定制)
  - name: "cn"                 # 最终生成的文件名 (如 cn.srs, cn.mrs)
    merge_from:
      - "applecn"              # 继承并合并名为 "applecn" 的子规则集
    # DNS 智能分流
    publish_dnsmasq: true      # 输出 dnsmasq 格式 (server=/domain/223.6.6.6)
    dnsmasq_server: "223.6.6.6" 
    publish_smartdns: true     # 输出 smartdns 格式
    smartdns_server: "china_group"
    
    # 上游订阅列表，引擎会智能选择 parser 解析器，亦可指定选择
    # parser 可用值： clash/v2ray/adblock/hosts/smartdns/dnsmasq/egern/stash/quantumultx/shadowrocket/loon/surge/white
    upstreams:
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt", parser: "clash"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list"}

  # 示例 2：去广告拦截规则集 (演示白名单行为与远程剔除)
  - name: "reject"
    # 白名单控制
    auto_extract_white: true   # 自动从上游 (如 adblock 格式) 提取 @@ 白名单
    publish_white: true        # 将提取的白名单单独输出一份文件
    white_name: "reject_white" # 自定义白名单文件名
    white_behavior: "remove"   # 可用值："remove" = 从主规则剔除并提取; 可用值："extract_only" = 仅提取，不进行剔除
    # DNS 拦截模式
    publish_adblock: true      # 输出 Adblock 兼容格式
    publish_smartdns: true     # 默认输出拦截语法 address=/domain/#
    publish_dnsmasq: true      # 默认输出拦截语法 address=/domain/0.0.0.0
    
    # 远程剔除列表 (引擎在去重时会自动剔除此列表中的规则)
    remove_urls:
      - {url: "https://raw.githubusercontent.com/217heidai/adblockfilters/refs/heads/main/rules/white.txt"}
    # 上游订阅列表
    upstreams:
      - {url: "https://anti-ad.net/clash.yaml"}
      - {url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt", parser: "adblock"}

  # 示例 3：纯本地规则 (不拉取任何上游)，name 必须和add/文件名一致
  - name: "local"
    upstreams: []             # 留空或删除这一行。引擎会自动读取 add/local.list 的本地文件

  - name: applecn
    upstreams:
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"}